# Generated by Django 4.0.5 on 2022-07-01 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curse',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('credits', models.PositiveSmallIntegerField()),
                ('teacher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fatherLastName', models.CharField(max_length=35)),
                ('motherLastName', models.CharField(max_length=35)),
                ('names', models.CharField(max_length=35)),
                ('dateBorn', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Males'), ('F', 'Female')], default='M', max_length=1)),
                ('isStudying', models.BooleanField(default=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.curse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.student')),
            ],
        ),
    ]
